import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const ROOT = join(import.meta.dirname, '..');

const COMMANDS: readonly { args: string[]; slug: string }[] = [
  { args: ['audit', '--help'], slug: 'audit' },
  { args: ['resume', '--help'], slug: 'resume' },
  { args: ['discard', '--help'], slug: 'discard' },
  { args: ['report', '--help'], slug: 'report' },
  { args: ['doctor', '--help'], slug: 'doctor' },
  { args: ['config', '--help'], slug: 'config' },
];

function captureHelp(args: string[]): string {
  const result = execFileSync(
    process.execPath,
    ['--import', 'tsx', join(ROOT, 'src', 'bw-organize.ts'), ...args],
    { encoding: 'utf-8', cwd: ROOT, timeout: 10_000 },
  );
  return result.replace(/\r\n/g, '\n').trimEnd();
}

function generateMarkdown(slug: string, helpText: string): string {
  const title = slug.charAt(0).toUpperCase() + slug.slice(1);
  const lines = [
    `# seiton ${slug}`,
    '',
    `> ${title} subcommand reference`,
    '',
    '```',
    helpText,
    '```',
    '',
    '---',
    '',
    '*This file is auto-generated by `scripts/gen-help-docs.ts`. Do not edit manually.*',
    '',
  ];
  return lines.join('\n');
}

function writeArtifact(relPath: string, content: string): void {
  const absPath = join(ROOT, relPath);
  mkdirSync(dirname(absPath), { recursive: true });
  writeFileSync(absPath, content, 'utf-8');
}

for (const cmd of COMMANDS) {
  const helpText = captureHelp(cmd.args);

  writeArtifact(`docs/commands/${cmd.slug}.md`, generateMarkdown(cmd.slug, helpText));
  writeArtifact(`test/fixtures/help/${cmd.slug}.txt`, helpText + '\n');

  console.log(`  docs/commands/${cmd.slug}.md`);
  console.log(`  test/fixtures/help/${cmd.slug}.txt`);
}

console.log('gen-help-docs: done');
