import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..', '..');

const COMMANDS = ['audit', 'resume', 'discard', 'report', 'doctor', 'config'];

describe('markdown doc content verification', () => {
  for (const cmd of COMMANDS) {
    it(`docs/commands/${cmd}.md contains the help text from the snapshot`, () => {
      const docPath = join(ROOT, 'docs', 'commands', `${cmd}.md`);
      const snapshotPath = join(ROOT, 'test', 'fixtures', 'help', `${cmd}.txt`);
      const docContent = readFileSync(docPath, 'utf-8');
      const helpText = readFileSync(snapshotPath, 'utf-8').trimEnd();

      assert.ok(
        docContent.includes(helpText),
        `docs/commands/${cmd}.md does not contain the full help text from the snapshot`,
      );
    });

    it(`docs/commands/${cmd}.md contains the auto-generation footer`, () => {
      const docPath = join(ROOT, 'docs', 'commands', `${cmd}.md`);
      const docContent = readFileSync(docPath, 'utf-8');

      assert.ok(
        docContent.includes('auto-generated by `scripts/gen-help-docs.ts`'),
        `docs/commands/${cmd}.md is missing the auto-generation footer`,
      );
    });

    it(`docs/commands/${cmd}.md contains a title heading`, () => {
      const docPath = join(ROOT, 'docs', 'commands', `${cmd}.md`);
      const docContent = readFileSync(docPath, 'utf-8');

      assert.ok(
        docContent.startsWith(`# seiton ${cmd}`),
        `docs/commands/${cmd}.md should start with "# seiton ${cmd}"`,
      );
    });
  }
});

describe('man page section coverage', () => {
  const manPath = join(ROOT, 'man', 'seiton.1');
  const content = readFileSync(manPath, 'utf-8');

  it('contains a COMMANDS section with known subcommands', () => {
    assert.ok(content.includes('.SH COMMANDS'), 'man page missing .SH COMMANDS section');

    const expectedCommands = ['audit', 'resume', 'discard', 'report', 'doctor', 'config show'];
    for (const cmd of expectedCommands) {
      assert.ok(
        content.includes(`.B ${cmd}`),
        `man page COMMANDS section missing "${cmd}"`,
      );
    }
  });

  it('contains an OPTIONS section with known flags', () => {
    assert.ok(content.includes('.SH OPTIONS'), 'man page missing .SH OPTIONS section');

    const expectedFlags = [
      '\\-\\-config',
      '\\-\\-dry\\-run',
      '\\-\\-json',
      '\\-\\-no\\-color',
      '\\-\\-verbose',
      '\\-\\-quiet',
      '\\-\\-help',
      '\\-\\-version',
    ];
    for (const flag of expectedFlags) {
      assert.ok(
        content.includes(flag),
        `man page OPTIONS section missing flag "${flag}"`,
      );
    }
  });

  it('contains an ENVIRONMENT section with known variables', () => {
    assert.ok(content.includes('.SH ENVIRONMENT'), 'man page missing .SH ENVIRONMENT section');

    const expectedVars = ['BW_SESSION', 'SEITON_CONFIG', 'SEITON_VERBOSE', 'NO_COLOR', 'CI', 'VISUAL', 'EDITOR'];
    for (const envVar of expectedVars) {
      assert.ok(
        content.includes(`.B ${envVar}`),
        `man page ENVIRONMENT section missing variable "${envVar}"`,
      );
    }
  });

  it('contains a FILES section with expected paths', () => {
    assert.ok(content.includes('.SH FILES'), 'man page missing .SH FILES section');

    const expectedPaths = [
      '$XDG_CONFIG_HOME/seiton/config.json',
      '$XDG_STATE_HOME/seiton/pending.json',
      '$HOME/.config/seiton/config.json',
      '$HOME/.seitonrc.json',
    ];
    for (const filePath of expectedPaths) {
      assert.ok(
        content.includes(filePath),
        `man page FILES section missing path "${filePath}"`,
      );
    }
  });

  it('contains a NAME section', () => {
    assert.ok(content.includes('.SH NAME'), 'man page missing .SH NAME section');
    assert.ok(content.includes('interactive Bitwarden vault auditor'), 'man page NAME missing description');
  });

  it('contains a SYNOPSIS section', () => {
    assert.ok(content.includes('.SH SYNOPSIS'), 'man page missing .SH SYNOPSIS section');
  });

  it('contains a DESCRIPTION section', () => {
    assert.ok(content.includes('.SH DESCRIPTION'), 'man page missing .SH DESCRIPTION section');
  });

  it('contains a SEE ALSO section', () => {
    assert.ok(content.includes('.SH SEE ALSO'), 'man page missing .SH SEE ALSO section');
    assert.ok(content.includes('bw (1)'), 'man page SEE ALSO missing bw(1) reference');
  });
});

describe('gen:docs idempotency', () => {
  it('running gen:docs twice produces identical output', () => {
    const genDocs = () => {
      execFileSync(
        process.execPath,
        ['--import', 'tsx', join(ROOT, 'scripts', 'gen-help-docs.ts')],
        { cwd: ROOT, timeout: 30_000 },
      );
    };

    genDocs();
    const firstRun: Record<string, string> = {};
    for (const cmd of COMMANDS) {
      firstRun[`docs/${cmd}`] = readFileSync(join(ROOT, 'docs', 'commands', `${cmd}.md`), 'utf-8');
      firstRun[`fixture/${cmd}`] = readFileSync(join(ROOT, 'test', 'fixtures', 'help', `${cmd}.txt`), 'utf-8');
    }

    genDocs();
    for (const cmd of COMMANDS) {
      const docContent = readFileSync(join(ROOT, 'docs', 'commands', `${cmd}.md`), 'utf-8');
      assert.equal(
        docContent,
        firstRun[`docs/${cmd}`],
        `docs/commands/${cmd}.md differs between gen:docs runs — generator is not idempotent`,
      );

      const fixtureContent = readFileSync(join(ROOT, 'test', 'fixtures', 'help', `${cmd}.txt`), 'utf-8');
      assert.equal(
        fixtureContent,
        firstRun[`fixture/${cmd}`],
        `test/fixtures/help/${cmd}.txt differs between gen:docs runs — generator is not idempotent`,
      );
    }
  });

  it('running gen-man twice on the same day produces identical output', () => {
    const genMan = () => {
      execFileSync(
        process.execPath,
        ['--import', 'tsx', join(ROOT, 'scripts', 'gen-man.ts')],
        { cwd: ROOT, timeout: 30_000 },
      );
    };

    genMan();
    const firstContent = readFileSync(join(ROOT, 'man', 'seiton.1'), 'utf-8');

    genMan();
    const secondContent = readFileSync(join(ROOT, 'man', 'seiton.1'), 'utf-8');

    assert.equal(
      firstContent,
      secondContent,
      'man/seiton.1 differs between gen-man runs on the same day — generator is not idempotent',
    );
  });
});
